### ISSUE TITLE
Tunnel it outside of just LAN?

### ISSUE THREAD

**Issue by 3qdr** [dev6699/rspy#1]
I tried using ngrok to get it working without any sort of LAN but it just blackscreens, any ways to make the whole thing work over ngrok?

**Comment by dev6699** [comment]
Hey @3qdr thanks for trying out, ngrok tunnel is using https, kindly check out v0.0.2 which added support for wss protocol.

**Comment by 3qdr** [comment]
It works now, Thank you very much :)

**Comment by 3qdr** [comment]
Hello, is it possible to configure it so it optimizes the screenshots for less bandwidth used? since ngrok only allow a amount per session 
![image](https://github.com/user-attachments/assets/356a0c27-7c26-48d5-a3d8-fc9961ddc275)

or can it re-screenshot once every while or once every action?

or if you know any better software better than ngrok it is also very appreciated

**Comment by dev6699** [comment]
Can I know what you trying to achieve with ngrok?

It is doable to use jpeg encoding with lower quality instead of png to reduce image size and set a interval between each screenshots taken.

**Comment by 3qdr** [comment]
I was basically setting up a remote desktop for my school since my school laptop cannot install apps, so since ngrok is the only software that I am sort of familiar with so I used it . Ngrok doesn't seem to be "free" anymore so I was wondering if there is any way to compress internet traffic or if there are alternatives to ngrok

**Comment by dev6699** [comment]
Can use the flag option `-i 1s -q 100` in v0.0.3, check out the README for more instruction.

Higher interval can reduce the amount of images transfer over websocket, but it causes the feel of delay if you set at high value, do experiment with the value you are comfortable with.
Lower quality for lower image size.

Do note that you are putting your laptop at risk if you expose it publicly via ngrok, I'm not sure any authentication mechanism provided by ngrok.

Don't have other recommendation cause I mainly use this within my local network and bandwidth is not my concern.

**Comment by 3qdr** [comment]
Ok thank you very much
